/**
 * SplitFlow Deployment Script
 * ----------------------------
 * Deploys RoyaltyManager and RoyaltyDistributor contracts to Stellar Testnet
 * (or Mainnet) and outputs the contract IDs to a `.env.local` file.
 *
 * Prerequisites:
 *   - stellar CLI installed:  cargo install --locked stellar-cli --features opt
 *   - DEPLOYER_SECRET_KEY set in environment
 *   - Contracts built:        npm run contracts:build
 *
 * Usage:
 *   DEPLOYER_SECRET_KEY=S... npx ts-node scripts/deploy.ts [--network testnet|mainnet]
 */

import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';

// ── Config ─────────────────────────────────────────────────────────────────
const network = process.argv.includes('--network')
  ? process.argv[process.argv.indexOf('--network') + 1]
  : 'testnet';

const DEPLOYER_SECRET = process.env.DEPLOYER_SECRET_KEY;
if (!DEPLOYER_SECRET) {
  console.error('❌ DEPLOYER_SECRET_KEY env var is required.');
  process.exit(1);
}

const WASM_DIR = path.resolve(__dirname, '../target/wasm32-unknown-unknown/release');
const MANAGER_WASM = path.join(WASM_DIR, 'royalty_manager.wasm');
const DISTRIBUTOR_WASM = path.join(WASM_DIR, 'royalty_distributor.wasm');
const ENV_OUTPUT = path.resolve(__dirname, '../frontend/.env.local');

// ── Helpers ─────────────────────────────────────────────────────────────────
function run(cmd: string): string {
  console.log(`  $ ${cmd}`);
  const output = execSync(cmd, { encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] }).trim();
  return output;
}

function assertWasm(wasmPath: string) {
  if (!fs.existsSync(wasmPath)) {
    console.error(`❌ WASM not found: ${wasmPath}`);
    console.error('   Run: cargo build --target wasm32-unknown-unknown --release');
    process.exit(1);
  }
}

// ── Deploy ──────────────────────────────────────────────────────────────────
async function main() {
  console.log(`\n🟠 SplitFlow Deploy Script — network: ${network.toUpperCase()}\n${'─'.repeat(50)}`);

  // Validate WASM files
  assertWasm(MANAGER_WASM);
  assertWasm(DISTRIBUTOR_WASM);

  // 1. Deploy RoyaltyManager
  console.log('\n[1/4] Deploying RoyaltyManager...');
  const managerContractId = run(
    `stellar contract deploy \
      --wasm "${MANAGER_WASM}" \
      --network ${network} \
      --source-account ${DEPLOYER_SECRET} \
      --fee 1000000`
  );
  console.log(`  ✓ RoyaltyManager deployed: ${managerContractId}`);

  // Sleep to prevent TxBadSeq on the next deployment
  console.log('  Waiting 5s for sequence number increment...');
  await new Promise((r) => setTimeout(r, 5000));

  // 2. Deploy RoyaltyDistributor
  console.log('\n[2/4] Deploying RoyaltyDistributor...');
  const distributorContractId = run(
    `stellar contract deploy \
      --wasm "${DISTRIBUTOR_WASM}" \
      --network ${network} \
      --source-account ${DEPLOYER_SECRET} \
      --fee 1000000`
  );
  console.log(`  ✓ RoyaltyDistributor deployed: ${distributorContractId}`);

  // Sleep to wait for ledger closure and testnet RPC sync/propagation
  console.log('  Waiting 8s for testnet synchronization...');
  await new Promise((r) => setTimeout(r, 8000));

  // 3. Initialize RoyaltyManager (set admin)
  console.log('\n[3/4] Initializing RoyaltyManager...');
  // Derive deployer public key
  const deployerPublicKey = run(
    `stellar keys public-key ${DEPLOYER_SECRET} 2>/dev/null || stellar keys address ${DEPLOYER_SECRET}`
  );
  run(
    `stellar contract invoke \
      --id ${managerContractId} \
      --network ${network} \
      --source-account ${DEPLOYER_SECRET} \
      -- initialize \
      --admin ${deployerPublicKey}`
  );
  console.log('  ✓ RoyaltyManager initialized');

  // 3b. Initialize RoyaltyDistributor
  console.log('\n[3b] Initializing RoyaltyDistributor...');
  run(
    `stellar contract invoke \
      --id ${distributorContractId} \
      --network ${network} \
      --source-account ${DEPLOYER_SECRET} \
      -- initialize \
      --admin ${deployerPublicKey} \
      --manager_address ${managerContractId} \
      --token_address CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC`
  );
  console.log('  ✓ RoyaltyDistributor initialized');

  // 4. Write .env.local
  console.log('\n[4/4] Writing .env.local...');
  const envContent = `# Auto-generated by scripts/deploy.ts — ${new Date().toISOString()}
# Network: ${network.toUpperCase()}

NEXT_PUBLIC_SOROBAN_RPC_URL=https://soroban-${network}.stellar.org
NEXT_PUBLIC_NETWORK_PASSPHRASE=${network === 'testnet' ? 'Test SDF Network ; September 2015' : 'Public Global Stellar Network ; September 2015'}
NEXT_PUBLIC_MANAGER_CONTRACT_ID=${managerContractId}
NEXT_PUBLIC_DISTRIBUTOR_CONTRACT_ID=${distributorContractId}
NEXT_PUBLIC_XLM_SAC_ID=CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC
`;
  fs.writeFileSync(ENV_OUTPUT, envContent);
  console.log(`  ✓ Written to ${ENV_OUTPUT}`);

  console.log(`\n${'─'.repeat(50)}`);
  console.log('✅ Deployment complete!\n');
  console.log('  RoyaltyManager:    ', managerContractId);
  console.log('  RoyaltyDistributor:', distributorContractId);
  console.log('\n  Explore on Stellar Expert:');
  console.log(`  https://stellar.expert/explorer/${network}/contract/${managerContractId}`);
  console.log(`  https://stellar.expert/explorer/${network}/contract/${distributorContractId}\n`);
}

main().catch((err) => {
  console.error('\n❌ Deployment FAILED:', err.message ?? err);
  process.exit(1);
});
